const express = require('express')
const router = express.Router();

const userRouter = require('./userRouter')
const orderRouter = require('./orderRouter')
const requestRouter = require('./requestRouter')
const requestStatusRouter = require('./requestStatusRouter')
const requestTypeRouter = require('./requestTypeRouter')
const serviceRouter = require('./serviceRouter')
const orderStatusRouter = require('./orderStatusRouter')
const paymentRouter = require('./paymentRouter')
const saleRouter = require('./saleRouter')
const colorRouter = require('./colorRouter')
const materialRouter = require('./materialRouter')
const furnitureRouter = require('./furnitureRouter')
const sizeRouter = require('./sizeRouter')
const cutRouter = require('./cutRouter')
const categoryRouter = require('./categoryRouter')
const productRouter = require('./productRouter')

router
    .use('/user', userRouter)
    .use('/order', orderRouter)
    .use('/request', requestRouter)
    .use('/requestStatus', requestStatusRouter)
    .use('/requestType', requestTypeRouter)
    .use('/service', serviceRouter)
    .use('/orderStatus', orderStatusRouter)
    .use('/payment', paymentRouter)
    .use('/sale', saleRouter)
    .use('/color', colorRouter)
    .use('/material', materialRouter)
    .use('/furniture', furnitureRouter)
    .use('/size', sizeRouter)
    .use('/cut', cutRouter)
    .use('/category', categoryRouter)
    .use('/product', productRouter)

module.exports = router 